# Generated by Django 4.1.7 on 2023-04-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_goal_delete_savinggoal_deposit_total_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='total_saved',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='total_saved',
            new_name='account',
        ),
    ]
